export enum Role {
  SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ADMIN = 'ROLE_ADMIN',
  MANAGER = 'ROLE_MANAGER',
  USER = 'ROLE_USER',
  HR = 'ROLE_HR',
  SYSADMIN= 'ROLE_SYSADMIN',
  HEADADMIN ='ROLE_HEADADMIN',
  HEADFIN ='ROLE_HEADFIN',
  HEADPROCUREMENT ='ROLE_HEADPROCUREMENT',
  
}


